version: "3.9"
services:
  api:
    build: ./
    image: cnab-importer:latest
    depends_on:
      - mysql
    environment:
      - ASPNETCORE_URLS=http://+:8080
      - ConnectionStrings__Default=Server=mysql;Port=3306;Database=cnab;User=cnab;Password=cnab
    ports:
      - "8080:8080"
  mysql:
    image: mysql:8.4
    environment:
      MYSQL_DATABASE: cnab
      MYSQL_USER: cnab
      MYSQL_PASSWORD: cnab
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - pgdata:/var/lib/mysql
volumes:
  pgdata: {}